In [363]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from proj1_helpers import *
from helpers import *
from implementations import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [364]:
DATA_TRAIN_PATH = 'data/train.csv' 
y, full_tX, ids = load_csv_data(DATA_TRAIN_PATH)

Reduce dimensions and standardize the columns of X

In [365]:
full_tX_red = full_tX[:, [0, 1, 2, 3, 8, 9, 10, 11, 13, 19, 21, 22, 29]]
full_tX_red_norm = standardize(full_tX_red)

Chunk the training set

In [366]:
tX_train = full_tX_red_norm[:80000][:].copy()
tX_train = build_poly(tX_train, 4)
y_train = y[:80000][:].copy()[:, np.newaxis]
tX_train[0]

array([ 1.00000000e+00,  4.61413715e-01,  6.83319669e-02,  4.07680272e-01,
       -4.69966242e-01,  1.03309853e+00,  3.39894409e-01,  1.70928751e-01,
        1.27708372e+00, -2.70810701e-01, -7.56756847e-01,  3.86846731e-01,
        1.04440205e+00,  4.12510497e-01,  2.12902616e-01,  4.66925770e-03,
        1.66203205e-01,  2.20868269e-01,  1.06729257e+00,  1.15528209e-01,
        2.92166381e-02,  1.63094282e+00,  7.33384356e-02,  5.72680926e-01,
        1.49650393e-01,  1.09077565e+00,  1.70164910e-01,  9.82361872e-02,
        3.19059563e-04,  6.77577677e-02, -1.03800630e-01,  1.10261838e+00,
        3.92673924e-02,  4.99396346e-03,  2.08285051e+00, -1.98608331e-02,
       -4.33380212e-01,  5.78917654e-02,  1.13920833e+00,  7.01948118e-02,
        4.53275241e-02,  2.18019675e-05,  2.76235052e-02,  4.87827922e-02,
        1.13911342e+00,  1.33467671e-02,  8.53611939e-04,  2.65997447e+00,
        5.37852613e-03,  3.27963443e-01,  2.23952402e-02,  1.18979152e+00,
        2.89560967e-02])

Augment the training set with the constant w0

In [ ]:
w = np.random.rand(tX_train.shape[1], 1)
w_final, loss = logistic_regression(y_train, tX_train, w, 5000, 0.1, verbose=True)

/home/flo/EPFL/ML/ML-Project-01/helpers.py:138: RuntimeWarning: overflow encountered in exp
  exp = np.exp(tx @ w)


Iteration : 0 with loss [[inf]] and gradient [[ 1.91908464e+00]
 [ 6.84296048e-01]
 [ 7.73620256e-01]
 [-2.74640174e-01]
 [-1.55102057e+00]
 [-1.07427391e+00]
 [-1.55826421e+00]
 [ 1.48891742e+00]
 [-1.99483436e+00]
 [-1.52951273e+00]
 [-9.59245999e-01]
 [-1.13713912e+00]
 [-1.92252385e+00]
 [-1.43056133e+00]
 [ 2.44002308e-01]
 [ 3.11861337e-01]
 [ 3.93037513e-02]
 [ 1.25354804e+00]
 [ 6.01361921e-01]
 [ 1.26528414e+00]
 [ 1.15517317e+00]
 [ 2.07357405e+00]
 [ 1.21902346e+00]
 [ 4.79474885e-01]
 [ 6.73803206e-01]
 [ 1.92596921e+00]
 [ 1.06639679e+00]
 [ 8.70049250e-02]
 [ 1.25717356e-01]
 [-5.62475927e-03]
 [-1.01312822e+00]
 [-3.36633104e-01]
 [-1.02738928e+00]
 [ 8.96238459e-01]
 [-2.15542175e+00]
 [-9.71563143e-01]
 [-2.39663408e-01]
 [-3.99257005e-01]
 [-1.92942076e+00]
 [-7.94934200e-01]
 [ 3.10237105e-02]
 [ 5.06791057e-02]
 [ 8.04959215e-04]
 [ 8.18818861e-01]
 [ 1.88442006e-01]
 [ 8.34222686e-01]
 [ 6.95344556e-01]
 [ 2.24050011e+00]
 [ 7.74336976e-01]
 [ 1.19794698e-01]
 [ 2.

In [ ]:
y_test = y[80000:90000][:].copy()[:,np.newaxis]
tX_test = full_tX_red_norm[80000:90000][:].copy()
tX_test = build_poly(tX_test, 4)
compute_accuracy(y_test, tX_test, w_final)

In [ ]:
compute_accuracy(y_train, tX_train, w_final)

## Generate predictions and save ouput in csv format for submission:


In [10]:
DATA_TEST_PATH = '' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

In [346]:
a = np.random.rand(30)
np.around(a)

array([1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [347]:
a

array([0.98948792, 0.67934654, 0.34673991, 0.48885077, 0.5348651 ,
       0.08436905, 0.02071519, 0.18776387, 0.52188862, 0.85832073,
       0.50843456, 0.60499752, 0.84728409, 0.93295583, 0.00486189,
       0.66121463, 0.3157777 , 0.6534353 , 0.12888288, 0.54033186,
       0.44024959, 0.37952039, 0.0833081 , 0.55721317, 0.36309742,
       0.2762448 , 0.46041519, 0.00914704, 0.35695435, 0.45490402])