In [57]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from proj1_helpers import *
from helpers import *
from implementations import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [95]:
def load_data(sub_sample=True, add_outlier=False):
    """Load data and convert it to the metric system."""
    path_dataset = "data/height_weight_genders.csv"
    data = np.genfromtxt(
        path_dataset, delimiter=",", skip_header=1, usecols=[1, 2])
    height = data[:, 0]
    weight = data[:, 1]
    gender = np.genfromtxt(
        path_dataset, delimiter=",", skip_header=1, usecols=[0],
        converters={0: lambda x: 0 if b"Male" in x else 1})
    # Convert to metric system
    height *= 0.025
    weight *= 0.454
    return height, weight, gender

In [96]:
def standardize(x):
    """Standardize the original data set."""
    mean_x = np.mean(x, axis=0)
    x = x - mean_x
    std_x = np.std(x, axis=0)
    x = x / std_x
    return x, mean_x, std_x

In [97]:
# load data.
height, weight, gender = load_data()

# build sampled x and y.
seed = 1
y = np.expand_dims(gender, axis=1)
X = np.c_[height.reshape(-1), weight.reshape(-1)]
y, X = sample_data(y, X, seed, size_samples=200)
x, mean_x, std_x = standardize(X)

In [98]:
tX_aug = np.hstack((np.ones((x.shape[0], 1)), x))
tX_aug.shape

(200, 3)

In [99]:
w = np.random.rand(x.shape[1], 1)# np.newaxis]# + 1)
w.shape
w

array([[0.55451053],
       [0.99332039]])

In [100]:
print(x.shape, y.shape, w.shape)

(200, 2) (200, 1) (2, 1)


In [101]:
w_final, loss = logistic_regression(y, x, w, 1000, 0.01)

(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[123.66443421]
 [135.93914515]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[25.21222466]
 [37.02825933]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[10.64371856]
 [21.82138808]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[ 5.64517434]
 [16.42592687]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[ 2.99957224]
 [13.47529363]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[ 1.3540127 ]
 [11.57351859]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[ 0.23733111]
 [10.23094797]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[-0.56245578]
 [ 9.22599545]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[-1.15615291]
 [ 8.4422519 ]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[-1.60780143]
 [ 7.81213579]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[-1.95720607]
 [ 7.29347368]]
(200, 2) (2, 1) (200, 1)
(200, 1)
(200, 1)
(2, 200)
[[-2.23051498]
 [ 6.85846227]]
(2

In [102]:
loss

array([[41.23698916]])